AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation script to provision ec2 instances
Parameters: 
  InstanceImageId:
    Description: image Id of the ec2 instance
    Type: AWS::EC2::Image::Id
  InstanceType:
    Description: Instance Type of the server
    Type: String
  

Resources: 
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: udacity
      ImageId: !Ref InstanceImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref MyInstanceSecurityGroup
      # UserData: !Base64 |
      #   #!/bin/bash -ex
      #   # put your script here
      Tags:
        - Key: Name
          Value: CircleCI-EC2-Instance
  MyInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Instance security Group to enable ssh access on port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
Outputs: